version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes: 
      - db:/var/lib/postdgresql/data
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KUMULUZEE_NAME=${MICROSERVICE_NAME}
      - KUMULUZEE_DATASOURCES0_USERNAME=${POSTGRES_USER}
      - KUMULUZEE_DATASOURCES0_PASSWORD=${POSTGRES_PASSWORD}
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/${DB_NAME}
    ports:
      - "127.0.0.1:${LOCAL_PORT}:8080"
    depends_on:
      - postgres
volumes:
  db:
    driver: local